### ISSUE TITLE
CRC16 mismatch in received data from Thermostat

### ISSUE THREAD

**Issue by pi4r0n** [midstar/heatmiser_wifi_ha#1]
I am trying to connect to my Heatmiser, I am sure my configured are right, but I think they might have changed the API and things aren't working anymore.  Anyone can point me on the right track? I have also enabled Legacy APi on their app in case anyone needs that info.

CONFIG
```
climate:
  - platform: heatmiser_wifi
    host: 192.168.0.3
    port: 4242 - I have also tried the default port, but it does not work
    friendly_name: Heatmiser
```

LOG
```
2022-02-07 08:18:08 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration heatmiser_wifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-07 08:18:35 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform heatmiser_wifi is taking over 10 seconds.
2022-02-07 08:18:35 ERROR (MainThread) [homeassistant.components.climate] heatmiser_wifi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/heatmiser_wifi/climate.py", line 169, in update
    self._heatmiser_info = self._heatmiser.get_info()
  File "/usr/local/lib/python3.9/site-packages/heatmiser_wifi/heatmiser_wifi.py", line 183, in get_info
    dcb = self.get_dcb()
  File "/usr/local/lib/python3.9/site-packages/heatmiser_wifi/heatmiser_wifi.py", line 155, in get_dcb
    (dcb_start, dcb_data) = self._receive_dcb()
  File "/usr/local/lib/python3.9/site-packages/heatmiser_wifi/heatmiser_wifi.py", line 126, in _receive_dcb
    raise Exception("CRC16 mismatch in received data from Thermostat")
Exception: CRC16 mismatch in received data from Thermostat
```

**Comment by midstar** [comment]
Which model of WiFi thermostat do you have? Only DT, DT-E, PRT models are supported by the protocol. However in reality I think it is only the PRT model that had WiFi. Note that all these models was stopped being produced many years ago.

Newer Heatmiser WiFi thermostat, called Neo, are connected to network through a separate component called NeoHub. NeoHub has another protocol. It seems to be a component availale on HACS called Heatmiser Neo Integration that should to the trick.
